---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [grafana, grafana-install]

- include: configure.yml
  tags: [grafana, grafana-configure]

- include: users.yml
  tags: [grafana, grafana-users]
  when: grafana_users|length > 0
